### ISSUE TITLE
Model requests: Vision Transformer

### ISSUE THREAD

**Issue by KentaItakura** [matlab-deep-learning/MATLAB-Deep-Learning-Model-Hub#1]
Do you have a plan to implement Vision Transformer? I would like to use it in MATLAB.

**Comment by davidwillingham** [comment]
Hi @KentaItakura, thanks for submitting this request.  We're looking into adding support for Vision Transformers. When there are updates to share, this issue will be updated as well.

**Comment by KentaItakura** [comment]
Hi, @davidwillingham, thanks for your update. I am looking forward to hearing from you about ViT.
