### ISSUE TITLE
Pretrained PointNet++

### ISSUE THREAD

**Issue by Keriedl** [matlab-deep-learning/MATLAB-Deep-Learning-Model-Hub#4]
Dear Sir or Madam,

i am training a PointNet++ architecture now for many weeks. However training does not converge at all. The datset contains 100 unique pointclouds (pc_size: 2000 or 20.000) and with data augmentation i get additional 100 (total: 200). I tried it with 2-4 Labels and many different training parameters. I hope you can help me with a pretrained model, which i can then transfer for my task.
Thanks in advance.

Best regards.
![training](https://user-images.githubusercontent.com/61782659/194378132-0d94b309-e8ed-41fc-bc15-85c0a4e494ad.png)

**Comment by davidwillingham** [comment]
Hi, we have a pointnet++ pretrained model listed in our Model Hub. Here is the link: 
https://www.mathworks.com/help/lidar/ug/aerial-lidar-segmentation-using-pointnet-network.html

There is access to a pretrained model in the example for the application of Aerial Lidar Semantic Segmentation in it, which you can load by:
>> load('pointnetplusTrained','net');

What application are you trying to train a pointnet++ model for? Is there a link to the code or data you're working with that you can share?

**Comment by davidwillingham** [comment]
example given
